"""
LifeSync AI — Google Docs API Service Module
Powers: meeting notes auto-draft, weekly plan document generation,
        tone-aware communication drafting, template library with AI fill,
        follow-up sequencer document creation.
"""
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from typing import List, Dict, Any, Optional
from datetime import datetime, timezone
import logging

logger = logging.getLogger(__name__)


class DocsService:
    """Service-oriented Google Docs module — independently testable."""

    def __init__(self, credentials: Credentials):
        self.docs_service = build("docs", "v1", credentials=credentials)
        self.drive_service = build("drive", "v3", credentials=credentials)

    # ── Document creation ─────────────────────────────────────────────────────

    def create_document(self, title: str) -> Dict:
        """Create a new Google Doc and return its ID and URL."""
        try:
            doc = self.docs_service.documents().create(body={"title": title}).execute()
            doc_id = doc.get("documentId")
            return {
                "doc_id": doc_id,
                "title": title,
                "url": f"https://docs.google.com/document/d/{doc_id}/edit",
                "status": "created",
            }
        except Exception as e:
            logger.error(f"DocsService.create_document error: {e}")
            return {"error": str(e)}

    def append_content(self, doc_id: str, content: str) -> Dict:
        """Append formatted content to an existing Google Doc."""
        try:
            requests = [
                {
                    "insertText": {
                        "location": {"index": 1},
                        "text": content,
                    }
                }
            ]
            result = self.docs_service.documents().batchUpdate(
                documentId=doc_id,
                body={"requests": requests},
            ).execute()
            return {"status": "updated", "replies": len(result.get("replies", []))}
        except Exception as e:
            logger.error(f"DocsService.append_content error: {e}")
            return {"error": str(e)}

    # ── Meeting notes generation ───────────────────────────────────────────────

    def create_meeting_notes(
        self,
        meeting_title: str,
        attendees: List[str],
        brain_dump: str,
        action_items: List[str],
        date: Optional[str] = None,
    ) -> Dict:
        """
        Auto-draft meeting notes after a calendar event ends.
        Input: voice/text brain dump → structured Google Doc.
        """
        try:
            date_str = date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
            title = f"Meeting Notes — {meeting_title} — {date_str}"
            doc_result = self.create_document(title)

            if "error" in doc_result:
                return doc_result

            attendee_list = "\n".join(f"  • {a}" for a in attendees) or "  • (no attendees recorded)"
            action_list = "\n".join(f"  ☐ {item}" for item in action_items) or "  • (none recorded)"

            content = f"""MEETING NOTES
Generated by LifeSync AI

Meeting: {meeting_title}
Date: {date_str}
Attendees:
{attendee_list}

─────────────────────────────
SUMMARY / BRAIN DUMP
─────────────────────────────
{brain_dump}

─────────────────────────────
ACTION ITEMS
─────────────────────────────
{action_list}

─────────────────────────────
Generated by LifeSync AI · {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
"""
            self.append_content(doc_result["doc_id"], content)
            return {**doc_result, "type": "meeting_notes"}
        except Exception as e:
            logger.error(f"DocsService.create_meeting_notes error: {e}")
            return {"error": str(e)}

    # ── Weekly plan document ───────────────────────────────────────────────────

    def create_weekly_plan(
        self,
        week_start: str,
        top_priorities: List[str],
        must_dos: List[str],
        focus_areas: List[str],
        goal_progress: List[Dict],
        review_summary: str,
    ) -> Dict:
        """
        Generate one-page weekly plan as a structured Google Doc.
        Created every Sunday for the coming week.
        """
        try:
            title = f"Weekly Plan — Week of {week_start}"
            doc_result = self.create_document(title)

            if "error" in doc_result:
                return doc_result

            priorities_text = "\n".join(f"  {i+1}. {p}" for i, p in enumerate(top_priorities[:3]))
            must_dos_text = "\n".join(f"  ☐ {m}" for m in must_dos[:5])
            focus_text = "\n".join(f"  → {f}" for f in focus_areas[:3])
            goals_text = "\n".join(
                f"  • {g.get('goal', 'Goal')}: {g.get('progress', 0)}% complete — {g.get('note', '')}"
                for g in goal_progress[:5]
            )

            content = f"""WEEKLY PLAN
Generated by LifeSync AI

Week Starting: {week_start}

═══════════════════════════════════════
TOP 3 PRIORITIES THIS WEEK
═══════════════════════════════════════
{priorities_text}

═══════════════════════════════════════
MUST-DOS (non-negotiable)
═══════════════════════════════════════
{must_dos_text}

═══════════════════════════════════════
FOCUS AREAS
═══════════════════════════════════════
{focus_text}

═══════════════════════════════════════
GOAL PROGRESS
═══════════════════════════════════════
{goals_text}

═══════════════════════════════════════
LAST WEEK IN REVIEW
═══════════════════════════════════════
{review_summary}

─────────────────────────────
Generated by LifeSync AI · {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
"""
            self.append_content(doc_result["doc_id"], content)
            return {**doc_result, "type": "weekly_plan"}
        except Exception as e:
            logger.error(f"DocsService.create_weekly_plan error: {e}")
            return {"error": str(e)}

    # ── Communication draft ───────────────────────────────────────────────────

    def create_communication_draft(
        self,
        doc_type: str,
        recipient: str,
        subject: str,
        content: str,
        tone: str = "professional",
    ) -> Dict:
        """
        Save a tone-aware communication draft to Google Docs.
        Types: proposal, status_update, follow_up, apology, request.
        """
        try:
            title = f"Draft — {doc_type.replace('_', ' ').title()} — {recipient} — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
            doc_result = self.create_document(title)

            if "error" in doc_result:
                return doc_result

            full_content = f"""COMMUNICATION DRAFT
Generated by LifeSync AI

Type: {doc_type.replace('_', ' ').title()}
To: {recipient}
Subject: {subject}
Tone: {tone.capitalize()}
Date: {datetime.now(timezone.utc).strftime("%Y-%m-%d")}

─────────────────────────────
DRAFT CONTENT
─────────────────────────────

{content}

─────────────────────────────
Note: Review before sending. Generated by LifeSync AI.
"""
            self.append_content(doc_result["doc_id"], full_content)
            return {**doc_result, "type": "communication_draft", "draft_type": doc_type, "tone": tone}
        except Exception as e:
            logger.error(f"DocsService.create_communication_draft error: {e}")
            return {"error": str(e)}

    # ── Document listing ──────────────────────────────────────────────────────

    def list_recent_docs(self, max_results: int = 10) -> List[Dict]:
        """List recently created LifeSync docs from Drive."""
        try:
            result = self.drive_service.files().list(
                q="mimeType='application/vnd.google-apps.document' and name contains 'LifeSync'",
                pageSize=max_results,
                orderBy="modifiedTime desc",
                fields="files(id,name,modifiedTime,webViewLink)",
            ).execute()
            return [
                {
                    "id": f.get("id"),
                    "title": f.get("name"),
                    "modified": f.get("modifiedTime"),
                    "url": f.get("webViewLink"),
                }
                for f in result.get("files", [])
            ]
        except Exception as e:
            logger.error(f"DocsService.list_recent_docs error: {e}")
            return []


# ── Mock implementation for testing ──────────────────────────────────────────

class MockDocsService:
    """Complete mock for unit testing without live Docs API calls."""

    def create_document(self, title: str) -> Dict:
        return {"doc_id": "mock_doc_abc123", "title": title, "url": "https://docs.google.com/document/d/mock_doc_abc123/edit", "status": "created"}

    def append_content(self, doc_id: str, content: str) -> Dict:
        return {"status": "updated", "replies": 1}

    def create_meeting_notes(self, meeting_title, attendees, brain_dump, action_items, date=None) -> Dict:
        return {
            "doc_id": "mock_meeting_notes_001",
            "title": f"Meeting Notes — {meeting_title}",
            "url": "https://docs.google.com/document/d/mock_meeting_notes_001/edit",
            "status": "created",
            "type": "meeting_notes",
        }

    def create_weekly_plan(self, week_start, top_priorities, must_dos, focus_areas, goal_progress, review_summary) -> Dict:
        return {
            "doc_id": "mock_weekly_plan_001",
            "title": f"Weekly Plan — Week of {week_start}",
            "url": "https://docs.google.com/document/d/mock_weekly_plan_001/edit",
            "status": "created",
            "type": "weekly_plan",
        }

    def create_communication_draft(self, doc_type, recipient, subject, content, tone="professional") -> Dict:
        return {
            "doc_id": "mock_comm_draft_001",
            "title": f"Draft — {doc_type} — {recipient}",
            "url": "https://docs.google.com/document/d/mock_comm_draft_001/edit",
            "status": "created",
            "type": "communication_draft",
            "draft_type": doc_type,
            "tone": tone,
        }

    def list_recent_docs(self, max_results=10) -> List[Dict]:
        return [
            {"id": "mock_doc_001", "title": "Meeting Notes — Team Standup — 2025-06-03", "modified": "2025-06-03T10:00:00Z", "url": "https://docs.google.com/document/d/mock_doc_001/edit"},
            {"id": "mock_doc_002", "title": "Weekly Plan — Week of 2025-06-02", "modified": "2025-06-02T08:00:00Z", "url": "https://docs.google.com/document/d/mock_doc_002/edit"},
        ]
